on:
  port: 8080
  
admin:
  port: 7070
  
app:
  brand: 'Hello world App'
  title: 'Hello world'
  search: true
  menu:
    portfolio: /portfolio
    About:
      About Us: /aboutUs
      About You: /aboutYou
    Admin: http://localhost:7070/_
    Page: NewFile.html
    
users:
  root:
    roles:
      - administrator
      - owner
    password: root # PLEASE change this